/**
 * Drizzle-схема, отражающая СУЩЕСТВУЮЩИЕ таблицы БД `karman_db`,
 * изначально созданные Django. Имена таблиц и колонок — snake_case, как в БД.
 *
 * Схема СВЕРЕНА с боевой БД через `pg_dump --schema-only` (2026-06-04):
 *  - первичные ключи и часть FK — bigint GENERATED BY DEFAULT AS IDENTITY
 *    (Django BigAutoField); `user_id` — integer (auth_user.id — int4).
 *  - У обычных колонок В БД НЕТ дефолтов: created_at/updated_at объявлены
 *    `.$defaultFn(...)`/`.$onUpdate(...)`, чтобы Drizzle ПЕРЕДАВАЛ значение при
 *    insert/update (иначе NOT NULL violation — дефолта на стороне БД нет).
 *  - Денежные колонки — numeric БЕЗ mode:'number' (Drizzle возвращает строкой;
 *    сохраняем конвенцию `::text`, избегаем float-дрейфа).
 */
import {
  bigint,
  boolean,
  date,
  integer,
  numeric,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

export type CreditStatus = 'active' | 'overdue' | 'closed';
export type PaymentStatus = 'scheduled' | 'overdue' | 'paid';
export type PaymentType = 'annuity' | 'differentiated' | 'other';

/** ISO-таймштамп для JS-side дефолтов (в БД нет DEFAULT now()). */
const isoNow = () => new Date().toISOString();

// --- Пользователи (Django auth_user; id — integer identity) -----------------
export const authUser = pgTable('auth_user', {
  id: serial('id').primaryKey(),
  password: varchar('password', { length: 128 }).notNull(),
  lastLogin: timestamp('last_login', { withTimezone: true, mode: 'string' }),
  isSuperuser: boolean('is_superuser').notNull().default(false),
  username: varchar('username', { length: 150 }).notNull(),
  firstName: varchar('first_name', { length: 150 }).notNull().$defaultFn(() => ''),
  lastName: varchar('last_name', { length: 150 }).notNull().$defaultFn(() => ''),
  email: varchar('email', { length: 254 }).notNull().$defaultFn(() => ''),
  isStaff: boolean('is_staff').notNull().default(false),
  isActive: boolean('is_active').notNull().default(true),
  dateJoined: timestamp('date_joined', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
});

// --- Банки / МФО (общий справочник, без user_id) ---------------------------
export const creditsBank = pgTable('credits_bank', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  name: varchar('name', { length: 200 }).notNull(),
  address: text('address').notNull().$defaultFn(() => ''),
  phone: varchar('phone', { length: 20 }).notNull().$defaultFn(() => ''),
  email: varchar('email', { length: 254 }).notNull().$defaultFn(() => ''),
  website: varchar('website', { length: 200 }).notNull().$defaultFn(() => ''),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow)
    .$onUpdate(isoNow),
});

// --- Кредиты ----------------------------------------------------------------
export const creditsCredit = pgTable('credits_credit', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  name: varchar('name', { length: 200 }).notNull().$defaultFn(() => ''),
  description: text('description'),
  amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
  interestRate: numeric('interest_rate', { precision: 5, scale: 2 }).notNull(),
  monthlyPayment: numeric('monthly_payment', { precision: 12, scale: 2 }),
  paymentType: varchar('payment_type', { length: 20 })
    .$type<PaymentType>()
    .notNull()
    .default('annuity'),
  startDate: date('start_date', { mode: 'string' }).notNull(),
  status: varchar('status', { length: 20 }).$type<CreditStatus>().notNull().default('active'),
  termMonths: integer('term_months').notNull(),
  bankId: bigint('bank_id', { mode: 'number' })
    .notNull()
    .references(() => creditsBank.id),
  userId: integer('user_id')
    .notNull()
    .references(() => authUser.id),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow)
    .$onUpdate(isoNow),
});

// --- Платежи по кредитам ----------------------------------------------------
// ВНИМАНИЕ: FK credit_id в БД — БЕЗ ON DELETE CASCADE; каскад делается в коде
// (см. deleteCredit). principal/interest — NOT NULL (для типа «other» пишем '0.00').
export const creditsPayment = pgTable('credits_payment', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  creditId: bigint('credit_id', { mode: 'number' })
    .notNull()
    .references(() => creditsCredit.id),
  amount: numeric('amount', { precision: 12, scale: 2 }).notNull(),
  principalAmount: numeric('principal_amount', { precision: 12, scale: 2 }).notNull(),
  interestAmount: numeric('interest_amount', { precision: 12, scale: 2 }).notNull(),
  dueDate: date('due_date', { mode: 'string' }).notNull(),
  paidDate: date('paid_date', { mode: 'string' }),
  status: varchar('status', { length: 20 }).$type<PaymentStatus>().notNull().default('scheduled'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow)
    .$onUpdate(isoNow),
});

// --- Категории документов (справочник, 8 строк) -----------------------------
export const documentsDocumentcategory = pgTable('documents_documentcategory', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  name: varchar('name', { length: 100 }).notNull(),
  description: text('description').notNull().$defaultFn(() => ''),
  icon: varchar('icon', { length: 50 }).notNull().$defaultFn(() => ''),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
});

// --- Документы пользователя -------------------------------------------------
export const documentsDocument = pgTable('documents_document', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  documentType: varchar('document_type', { length: 20 }).notNull().$defaultFn(() => ''),
  title: varchar('title', { length: 200 }).notNull(),
  description: text('description').notNull().$defaultFn(() => ''),
  documentNumber: varchar('document_number', { length: 100 }).notNull().$defaultFn(() => ''),
  issueDate: date('issue_date', { mode: 'string' }),
  expiryDate: date('expiry_date', { mode: 'string' }),
  issuingAuthority: varchar('issuing_authority', { length: 200 }).notNull().$defaultFn(() => ''),
  frontImage: varchar('front_image', { length: 100 }),
  backImage: varchar('back_image', { length: 100 }),
  additionalFiles: varchar('additional_files', { length: 100 }),
  isActive: boolean('is_active').notNull().default(true),
  userId: integer('user_id')
    .notNull()
    .references(() => authUser.id),
  categoryId: bigint('category_id', { mode: 'number' })
    .notNull()
    .references(() => documentsDocumentcategory.id),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
    .notNull()
    .$defaultFn(isoNow)
    .$onUpdate(isoNow),
});

// --- Связи ------------------------------------------------------------------
export const creditsBankRelations = relations(creditsBank, ({ many }) => ({
  credits: many(creditsCredit),
}));

export const creditsCreditRelations = relations(creditsCredit, ({ one, many }) => ({
  bank: one(creditsBank, { fields: [creditsCredit.bankId], references: [creditsBank.id] }),
  user: one(authUser, { fields: [creditsCredit.userId], references: [authUser.id] }),
  payments: many(creditsPayment),
}));

export const creditsPaymentRelations = relations(creditsPayment, ({ one }) => ({
  credit: one(creditsCredit, {
    fields: [creditsPayment.creditId],
    references: [creditsCredit.id],
  }),
}));

export const documentsDocumentRelations = relations(documentsDocument, ({ one }) => ({
  user: one(authUser, { fields: [documentsDocument.userId], references: [authUser.id] }),
  category: one(documentsDocumentcategory, {
    fields: [documentsDocument.categoryId],
    references: [documentsDocumentcategory.id],
  }),
}));

export type AuthUserRow = typeof authUser.$inferSelect;
export type BankRow = typeof creditsBank.$inferSelect;
export type CreditRow = typeof creditsCredit.$inferSelect;
export type PaymentRow = typeof creditsPayment.$inferSelect;
export type DocumentRow = typeof documentsDocument.$inferSelect;
export type DocumentCategoryRow = typeof documentsDocumentcategory.$inferSelect;
