-- 0001_telegram_reminders — система напоминаний с доставкой в Telegram (P0).
--
-- РУКОПИСНАЯ миграция (НЕ drizzle-kit generate — миграций ещё не было вовсе, и
-- generate сгенерил бы baseline всех Django-таблиц). Только новые таблицы,
-- аддитивно, без ALTER существующих. Применяется на проде ВРУЧНУЮ через psql ДО
-- деплоя; migration-guard в deploy-prod.yml заблокирует авто-деплой → деплой
-- через workflow_dispatch. См. docs/telegram-reminders.md.
--
-- Конвенции схемы karman_db: snake_case, bigint identity PK, user_id int4 →
-- auth_user.id, timestamptz. На новых таблицах ставим DEFAULT now() (в отличие от
-- legacy Django-таблиц) — чтобы и Drizzle, и сырые INSERT диспетчера работали без
-- NOT NULL violation.

BEGIN;

-- Привязка Telegram-чата к пользователю (1:1).
CREATE TABLE IF NOT EXISTS telegram_link (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              integer NOT NULL UNIQUE REFERENCES auth_user (id),
  chat_id              bigint,
  link_code            varchar(64),
  link_code_expires_at timestamptz,
  tg_username          varchar(64),
  is_active            boolean NOT NULL DEFAULT true,
  mark_paid_enabled    boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS telegram_link_chat_id_uq
  ON telegram_link (chat_id) WHERE chat_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS telegram_link_link_code_uq
  ON telegram_link (link_code) WHERE link_code IS NOT NULL;

-- Определение напоминания.
CREATE TABLE IF NOT EXISTS reminder (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        integer NOT NULL REFERENCES auth_user (id),
  title          varchar(200) NOT NULL,
  body_template  text NOT NULL DEFAULT '',
  source_type    varchar(20) NOT NULL DEFAULT 'freeform',
  source_id      bigint,
  rule_id        varchar(40),
  priority       varchar(10) NOT NULL DEFAULT 'normal',
  silent         boolean NOT NULL DEFAULT false,
  status         varchar(12) NOT NULL DEFAULT 'active',
  timezone       varchar(40) NOT NULL DEFAULT 'Europe/Moscow',
  attachment_ref varchar(120),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
-- Ключ идемпотентного апсерта доменных авто-напоминаний (P4): один reminder на
-- (пользователь, источник, правило). freeform-напоминания под ключ не попадают.
CREATE UNIQUE INDEX IF NOT EXISTS reminder_source_uq
  ON reminder (user_id, source_type, source_id, rule_id)
  WHERE source_type <> 'freeform';
CREATE INDEX IF NOT EXISTS reminder_user_id_idx ON reminder (user_id);

-- Расписание (1:1 с reminder). spec — гибкая jsonb-спека; next_fire_at —
-- нормализованный UTC-инстант, единственное, что читает горячий due-scan.
CREATE TABLE IF NOT EXISTS reminder_schedule (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reminder_id   bigint NOT NULL REFERENCES reminder (id) ON DELETE CASCADE,
  spec          jsonb NOT NULL,
  next_fire_at  timestamptz,
  last_fired_at timestamptz,
  fire_count    integer NOT NULL DEFAULT 0,
  end_at        timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS reminder_schedule_due_idx
  ON reminder_schedule (next_fire_at) WHERE next_fire_at IS NOT NULL;

-- Журнал срабатываний/отправок. UNIQUE (reminder_id, fire_slot) — главная защита
-- от двойной отправки на пересекающихся тиках диспетчера.
CREATE TABLE IF NOT EXISTS reminder_delivery (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reminder_id   bigint NOT NULL REFERENCES reminder (id) ON DELETE CASCADE,
  schedule_id   bigint REFERENCES reminder_schedule (id) ON DELETE SET NULL,
  fire_slot     timestamptz NOT NULL,
  status        varchar(12) NOT NULL DEFAULT 'pending',
  tg_chat_id    bigint,
  tg_message_id bigint,
  attempts      integer NOT NULL DEFAULT 0,
  last_error    text,
  sent_at       timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reminder_delivery_slot_uq UNIQUE (reminder_id, fire_slot)
);

-- Входящие нажатия кнопок (аудит + идемпотентность write-back).
-- UNIQUE (delivery_id, action) поглощает повторную доставку callback'а Telegram'ом.
CREATE TABLE IF NOT EXISTS reminder_action (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_id    bigint REFERENCES reminder_delivery (id) ON DELETE CASCADE,
  reminder_id    bigint NOT NULL REFERENCES reminder (id) ON DELETE CASCADE,
  user_id        integer NOT NULL,
  action         varchar(20) NOT NULL,
  payload        jsonb,
  tg_callback_id varchar(64),
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reminder_action_dedup_uq UNIQUE (delivery_id, action)
);

COMMIT;
