-- 0002_secrets_manager — зашифрованное хранилище секретов проектов (менеджер ключей).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Только новые
-- таблицы, аддитивно, без ALTER существующих. Применяется на проде ВРУЧНУЮ через
-- psql ДО деплоя (migration-guard в deploy-prod.yml заблокирует авто-деплой →
-- деплой через workflow_dispatch). Прод-ops на Боксе 1 — через brain (нет SSH).
--
-- Значения секретов хранятся ЗАШИФРОВАННЫМИ (AES-256-GCM; мастер-ключ
-- SECRETS_MASTER_KEY в env хоста, НЕ в БД). Токены доступа — только SHA-256-хэш.
-- Конвенции: snake_case, bigint identity PK, user_id int4 → auth_user.id, timestamptz,
-- DEFAULT now() на новых таблицах. См. docs/secrets-manager.md.

BEGIN;

-- Проект — группа секретов одного владельца.
CREATE TABLE IF NOT EXISTS secrets_project (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES auth_user (id),
  name       varchar(200) NOT NULL,
  slug       varchar(100) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
-- slug уникален в пределах владельца (человекочитаемый идентификатор проекта).
CREATE UNIQUE INDEX IF NOT EXISTS secrets_project_user_slug_uq
  ON secrets_project (user_id, slug);

-- Секрет: значение зашифровано AES-256-GCM (ciphertext/iv/auth_tag — base64).
CREATE TABLE IF NOT EXISTS secrets_item (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  key        varchar(200) NOT NULL,
  ciphertext text NOT NULL,
  iv         varchar(32) NOT NULL,
  auth_tag   varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_item_project_key_uq UNIQUE (project_id, key)
);

-- Токен доступа проекта (машинный). Хранится ТОЛЬКО SHA-256-хэш полного токена.
CREATE TABLE IF NOT EXISTS secrets_token (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id   bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  name         varchar(200) NOT NULL,
  token_prefix varchar(20) NOT NULL,
  token_hash   varchar(64) NOT NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
-- Поиск по хэшу при проверке токена — уникальный (хэш SHA-256 полного токена).
CREATE UNIQUE INDEX IF NOT EXISTS secrets_token_hash_uq ON secrets_token (token_hash);
CREATE INDEX IF NOT EXISTS secrets_token_project_idx ON secrets_token (project_id);

-- Аудит обращений (pull по токену, выдача/отказ). project_id/token_id nullable —
-- для логирования отказов по неизвестному токену.
CREATE TABLE IF NOT EXISTS secrets_audit (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint REFERENCES secrets_project (id) ON DELETE CASCADE,
  token_id   bigint REFERENCES secrets_token (id) ON DELETE SET NULL,
  action     varchar(40) NOT NULL,
  detail     text,
  ip         varchar(64),
  at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS secrets_audit_project_at_idx ON secrets_audit (project_id, at);

COMMIT;
