-- 0004_secrets_cards — карточки секретов (vault Ф1, план docs/secrets-vault-plan.md).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Только новые
-- таблицы, аддитивно, без ALTER существующих. Применяется на проде через psql
-- ДО деплоя (migration-guard в deploy-prod.yml заблокирует авто-деплой →
-- деплой через workflow_dispatch). См. docs/secrets-manager.md.
--
-- Карточка — человекочитаемый слой поверх env-пар: наименование (зашифровано),
-- программное обозначение (env_key, plaintext — связка с secrets_item и
-- уникальность в комнате; NULL у личных карточек) и произвольные поля.
-- Значения ВСЕХ полей шифруются AES-256-GCM (требование all-fields ADR-0006);
-- plaintext остаются только имена полей и env_key.

BEGIN;

CREATE TABLE IF NOT EXISTS secrets_card (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  env_key    varchar(200),
  -- Наименование карточки, AES-256-GCM (AAD привязывает к id карточки).
  title_ct   text NOT NULL,
  title_iv   varchar(32) NOT NULL,
  title_tag  varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS secrets_card_project_env_uq
  ON secrets_card (project_id, env_key) WHERE env_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS secrets_card_project_idx ON secrets_card (project_id);

-- Произвольное поле карточки. kind — подсказка отображения (text/secret/url),
-- шифруются значения всех kind одинаково. Колонка text — без обрезания длинных
-- значений (JWT/сертификаты целиком), кап 256 КБ — только в валидации.
CREATE TABLE IF NOT EXISTS secrets_card_field (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id    bigint NOT NULL REFERENCES secrets_card (id) ON DELETE CASCADE,
  name       varchar(200) NOT NULL,
  kind       varchar(10) NOT NULL DEFAULT 'text',
  ciphertext text NOT NULL,
  iv         varchar(32) NOT NULL,
  auth_tag   varchar(32) NOT NULL,
  position   integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_card_field_card_name_uq UNIQUE (card_id, name)
);

COMMIT;
