-- 0005_totp_2fa — второй фактор входа (TOTP) + аудит входов (vault Ф2,
-- план docs/secrets-vault-plan.md).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Только новые
-- таблицы, аддитивно, без ALTER существующих. Применяется на проде через psql
-- ДО деплоя (migration-guard заблокирует авто-деплой → workflow_dispatch).
--
-- TOTP-секрет хранится ЗАШИФРОВАННЫМ (AES-256-GCM мастер-ключом менеджера
-- секретов, AAD привязан к user_id). Recovery-коды — только SHA-256-хэши.

BEGIN;

-- Второй фактор пользователя. enabled_at NULL — enrollment начат, но не
-- подтверждён кодом (не активен); строка перезаписывается при новом enrollment.
CREATE TABLE IF NOT EXISTS auth_totp (
  user_id    integer PRIMARY KEY REFERENCES auth_user (id) ON DELETE CASCADE,
  secret_ct  text NOT NULL,
  secret_iv  varchar(32) NOT NULL,
  secret_tag varchar(32) NOT NULL,
  enabled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Одноразовые recovery-коды (fallback вместо TOTP-кода). В БД только хэш;
-- plaintext показывается владельцу один раз при включении 2FA.
CREATE TABLE IF NOT EXISTS auth_recovery_code (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
  code_hash  varchar(64) NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_recovery_code_user_idx ON auth_recovery_code (user_id);

-- Аудит входов (успех/провал/lockout/2FA). user_id nullable — провалы по
-- несуществующему логину тоже логируются.
CREATE TABLE IF NOT EXISTS auth_audit (
  id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  integer REFERENCES auth_user (id) ON DELETE SET NULL,
  username varchar(150),
  action   varchar(40) NOT NULL,
  ip       varchar(64),
  at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_audit_at_idx ON auth_audit (at);

COMMIT;
