-- 0006_secrets_grant — выдача доступа к ключу между комнатами (мандат brain 2026-07-26,
-- класс пробела — идея #091: изоляция по арендатору не оставляет маршрута общему секрету).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Только новая таблица,
-- аддитивно, без ALTER существующих. Применяется на проде через psql ДО деплоя
-- (migration-guard в deploy-prod.yml заблокирует авто-деплой → деплой через
-- workflow_dispatch). См. docs/secrets-manager.md.
--
-- Grant НЕ копирует значение: комната-получатель читает исходную запись комнаты-источника
-- своим токеном, под собственным именем (alias_key). Отзыв доступа не требует ротации
-- секрета, а ротация в источнике сразу видна всем получателям.

BEGIN;

CREATE TABLE IF NOT EXISTS secrets_grant (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Комната-источник и ключ в ней. Ключ хранится по ИМЕНИ, а не по id записи:
  -- grant можно выдать заранее (источник появится позже) и он переживает
  -- пересоздание записи.
  source_project_id bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  source_key        varchar(200) NOT NULL,
  -- Комната-получатель и имя, под которым она видит значение в своём GET /api/secrets.
  target_project_id bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  alias_key         varchar(200) NOT NULL,
  -- Кто инициатор выдачи (владелец от себя / по мандату brain и т.п.) — в аудит обеих сторон.
  note              text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  revoked_at        timestamptz,
  CONSTRAINT secrets_grant_not_self CHECK (source_project_id <> target_project_id)
);

-- Два действующих grant'а не могут занять одно имя у получателя (иначе значение
-- зависит от порядка выборки). Отозванные — не мешают.
CREATE UNIQUE INDEX IF NOT EXISTS secrets_grant_target_alias_uq
  ON secrets_grant (target_project_id, alias_key) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS secrets_grant_source_idx ON secrets_grant (source_project_id);
CREATE INDEX IF NOT EXISTS secrets_grant_target_idx ON secrets_grant (target_project_id);

COMMIT;
