-- 0007_ecosystem_passport — паспортный вход в vault (ADR-0012 мозга, волна 2).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Аддитивно:
-- четыре новые таблицы + два ALTER ... ADD COLUMN (без NOT NULL и без DEFAULT
-- на больших таблицах — существующие строки не переписываются). Применяется на
-- проде через psql ДО деплоя (migration-guard в deploy-prod.yml заблокирует
-- авто-деплой → деплой через workflow_dispatch). См. docs/passport-server.md.
--
-- Смысл: сущность «первый секрет» (общий VAULT_PROVISION_KEY) заменяется
-- короткоживущим подписанным удостоверением CI. Личность берётся из claim'а
-- подписи, а не из факта обладания строкой; авторизация — ровно своя комната.

BEGIN;

-- Доверенный issuer удостоверений. GitHub OIDC — первый акцептор, а НЕ архитектура:
-- собственный issuer (у setka уже работает OIDC-провайдер) добавляется строкой,
-- потребителей это не касается (ADR-0012 §2, vendor-neutrality ADR-0011).
CREATE TABLE IF NOT EXISTS passport_issuer (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer          varchar(300) NOT NULL UNIQUE,   -- значение claim `iss`
  jwks_uri        varchar(500) NOT NULL,
  audience        varchar(200) NOT NULL,          -- что обязан запросить клиент
  -- Регулярное выражение по claim `sub`: пин субъекта на основную ветку. Ветки,
  -- PR и форки личность НЕ минтят — проверяет провайдер, а не GitHub (защита
  -- ветки доступна не всем репо экосистемы, ADR-0012 «замер защиты веток»).
  subject_pattern varchar(300) NOT NULL,
  -- Claim с НЕИЗМЕНЯЕМЫМ числовым идентификатором личности: переименование
  -- аккаунта/репозитория не создаёт дыру, перехват освободившегося имени
  -- не даёт личности (ADR-0012 §5).
  identity_claim  varchar(60) NOT NULL,
  enabled         boolean NOT NULL DEFAULT true,
  note            text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Карта личность → комната. Заводится ЯВНО владельцем из живого /secrets;
-- автозаведение комнаты неизвестной личности и автовывод slug'а из имени репо
-- запрещены (вывод не инъективен, а в vault лежали мусорные комнаты).
CREATE TABLE IF NOT EXISTS passport_identity (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer_id      bigint NOT NULL REFERENCES passport_issuer (id) ON DELETE CASCADE,
  -- Значение identity_claim как строка (числовой id репозитория у GitHub OIDC).
  identity_value varchar(200) NOT NULL,
  -- Человекочитаемая метка (`Valstan/trener`) — ТОЛЬКО для UI и аудита,
  -- в проверке не участвует.
  label          varchar(200) NOT NULL,
  project_id     bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  -- Может ли сессия этой личности писать секреты (POST /api/secrets).
  can_write      boolean NOT NULL DEFAULT false,
  note           text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  -- Отзыв личности ОБЯЗАН гасить всё, что она выпустила (каскад отзыва,
  -- ADR-0012 §5): сервис при отзыве закрывает и её живые сессии.
  revoked_at     timestamptz
);

-- Две действующие личности не могут делить один identity_value у одного issuer'а.
CREATE UNIQUE INDEX IF NOT EXISTS passport_identity_value_uq
  ON passport_identity (issuer_id, identity_value) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS passport_identity_project_idx ON passport_identity (project_id);

-- Снимок JWKS для формы «удалённый JWKS + cooldown + stale-if-error»:
-- проверка подписи не должна падать вместе с чужим CDN (probe с Бокса 1 зелёный,
-- но доступность внешнего issuer'а — не наш инвариант).
CREATE TABLE IF NOT EXISTS passport_jwks_cache (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jwks_uri       varchar(500) NOT NULL UNIQUE,
  jwks           jsonb NOT NULL,
  fetched_at     timestamptz NOT NULL DEFAULT now(),
  -- Последняя неудача фетча: снимок продолжает работать, но факт виден.
  last_error     text,
  last_error_at  timestamptz
);

-- Одноразовость удостоверения (anti-replay). Строка пишется ТОЛЬКО при УСПЕХЕ:
-- иначе ретрай CI ломается о собственный anti-replay (ADR-0012 §5).
CREATE TABLE IF NOT EXISTS passport_assertion (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer_id  bigint NOT NULL REFERENCES passport_issuer (id) ON DELETE CASCADE,
  jti        varchar(200) NOT NULL,
  subject    text NOT NULL,
  -- exp удостоверения: по нему чистится таблица (хранить дольше смысла нет —
  -- истёкшее удостоверение и так не проходит проверку срока).
  expires_at timestamptz NOT NULL,
  used_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS passport_assertion_jti_uq
  ON passport_assertion (issuer_id, jti);
CREATE INDEX IF NOT EXISTS passport_assertion_expires_idx ON passport_assertion (expires_at);

-- Сессионный токен = обычный skm_-токен комнаты со СРОКОМ и привязкой к личности.
-- Так весь существующий контур (GET/POST /api/secrets, аудит, grant'ы) работает
-- без изменений, а самоотзыв и каскад отзыва личности ложатся на ту же таблицу.
-- Для токенов владельца обе колонки остаются NULL (бессрочный, ничей).
ALTER TABLE secrets_token ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE secrets_token ADD COLUMN IF NOT EXISTS identity_id bigint
  REFERENCES passport_identity (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS secrets_token_identity_idx ON secrets_token (identity_id);

-- Долг ADR-0012 §6: GUI-операции владельца не аудировались вовсе — в аудите не
-- было колонки актора, поэтому «кто» отличалось от «что предъявили» только по
-- косвенным признакам. NULL у старых строк читается как «актор неизвестен».
ALTER TABLE secrets_audit ADD COLUMN IF NOT EXISTS actor varchar(120);

-- Первый акцептор: GitHub OIDC. Строка issuer'а САМА ПО СЕБЕ доступа не даёт —
-- без явной строки passport_identity любое удостоверение получает 403.
INSERT INTO passport_issuer (issuer, jwks_uri, audience, subject_pattern, identity_claim, note)
VALUES (
  'https://token.actions.githubusercontent.com',
  'https://token.actions.githubusercontent.com/.well-known/jwks',
  'karman-vault',
  '^repo:[^:/]+/[^:/]+:ref:refs/heads/(main|master)$',
  'repository_id',
  'ADR-0012 волна 2: первый настроенный акцептор, не архитектура'
)
ON CONFLICT (issuer) DO NOTHING;

COMMIT;
