-- 0008_secrets_bootstrap — одноразовый bootstrap-код комнаты («времянка»).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Аддитивно:
-- одна новая таблица. Применяется на проде через psql ДО деплоя (migration-guard
-- заблокирует авто-деплой → деплой через workflow_dispatch).
--
-- Задача: отдать проекту его первый токен, не пересылая ничего долгоживущего.
-- Владелец выпускает код, код можно назвать вслух (чат, звонок), проект меняет
-- его на токен своей комнаты — и код в тот же момент гаснет.
--
-- Почему это НЕ ослабление, а усиление относительно того, что было:
--   * `VAULT_PROVISION_KEY` — общий, бессрочный, один на всю экосистему: утечка
--     требует действий у всех тринадцати проектов (тест на супер-ключ ADR-0012 §1
--     он НЕ проходит). Bootstrap-код одноразовый, живёт минуты и привязан к ОДНОЙ
--     комнате: утечка требует действий у одного проекта и истекает сама.
--   * Перехват кода ЗАМЕТЕН: легитимный обмен после чужого падает с 401, то есть
--     кража превращается в сломанный онбординг, а не в тихий доступ. Скопированная
--     долгоживущая строка не заметна вообще.
--   * Комната, наполненная владельцем до онбординга, self-serve-путём уже не
--     открывается (гейт девственности, ADR-0010) — код закрывает ровно этот тупик,
--     не ослабляя сам гейт.
--
-- Чего код НЕ делает: не заводит комнату, не даёт читать секреты сам по себе,
-- не продлевается и не выпускается повторно тем же значением.

BEGIN;

CREATE TABLE IF NOT EXISTS secrets_bootstrap (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id   bigint NOT NULL REFERENCES secrets_project (id) ON DELETE CASCADE,
  -- Только SHA-256 самого кода: в БД восстановимого значения нет, как у токенов.
  code_hash    varchar(64) NOT NULL,
  -- Начало кода для опознания в UI и аудите (значение по нему не подобрать).
  code_prefix  varchar(20) NOT NULL,
  -- Право будущего токена, зафиксированное в момент выпуска: получатель НЕ
  -- выбирает себе полномочия сам.
  can_write    boolean NOT NULL DEFAULT false,
  expires_at   timestamptz NOT NULL,
  -- Момент обмена. Заполнен → код мёртв навсегда (повторный обмен = 401).
  used_at      timestamptz,
  used_ip      varchar(64),
  -- Токен, выданный по этому коду: связка «времянка → что именно она породила»
  -- нужна при отзыве и при разборе инцидента.
  issued_token_id bigint REFERENCES secrets_token (id) ON DELETE SET NULL,
  note         text,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS secrets_bootstrap_hash_uq ON secrets_bootstrap (code_hash);
CREATE INDEX IF NOT EXISTS secrets_bootstrap_project_idx ON secrets_bootstrap (project_id);

COMMIT;
