-- Вход через ЕСА (единый вход экосистемы, OIDC) — задача владельца 2026-08-25.
--
-- Хранит связь «личность у внешнего провайдера -> пользователь КАРМАНа».
-- Пара (issuer, subject) уникальна: sub у OIDC-провайдера неизменяемый и
-- непереиспользуемый, привязка по нему, а НЕ по почте — почта у человека
-- меняется, и связь по ней означала бы смену владельца аккаунта при смене почты.
--
-- Почему отдельная таблица, а не колонка в auth_user: провайдеров может стать
-- больше одного, а у пользователя — несколько личностей (рабочая/личная).
-- Колонка это запретила бы, не сказав об этом.

create table if not exists auth_oidc_identity (
  id            bigint generated by default as identity primary key,
  issuer        varchar(255) not null,
  subject       varchar(255) not null,
  user_id       integer      not null references auth_user(id) on delete cascade,
  -- Почта на момент привязки — только для аудита и подсказки в UI.
  -- Решения по ней НЕ принимаются после привязки: см. комментарий выше.
  email         varchar(254),
  -- Как возникла связь: 'linked_by_email' (совпала подтверждённая почта
  -- существующего пользователя) или 'provisioned' (пользователь заведён
  -- этим входом). Нужно, чтобы потом отличать заведённых снаружи от своих.
  origin        varchar(32)  not null default 'provisioned',
  created_at    timestamptz  not null default now(),
  last_login_at timestamptz,
  constraint auth_oidc_identity_issuer_subject_key unique (issuer, subject)
);

create index if not exists auth_oidc_identity_user_id_idx on auth_oidc_identity (user_id);
