-- Веха 1 эпика «Личные данные и Круг Совиных» (заказ владельца 2026-09-03).
--
-- Карточка человека: то, что «постоянно спрашивают» — паспортные реквизиты,
-- СНИЛС, ИНН, прописка, место работы. Отдельная таблица, а не колонки в
-- auth_user, по трём причинам:
--   1. auth_user — наследие Django и участвует во ВСЕХ путях входа; каждая
--      новая колонка там расширяет строку, которую читает getCurrentUser на
--      каждом запросе.
--   2. Персональные данные и учётные — разный срок жизни и разный доступ:
--      учётку владелец отключает, карточку — отдаёт в круг по согласию.
--   3. Строку карточки надо уметь отдавать другому человеку целиком
--      (выгрузка по кругу), а строку auth_user — никогда: там хеш пароля.
--
-- Один профиль на пользователя: unique(user_id). Каскад по удалению
-- пользователя — карточка без хозяина смысла не имеет.

create table if not exists person_profile (
  id                    bigint generated by default as identity primary key,
  user_id               integer      not null references auth_user(id) on delete cascade,

  -- ФИО отдельными колонками, а не одной строкой: выгрузка по кругу выбирается
  -- галочками по ПОЛЯМ, и «фамилия отдельно» — самый частый такой выбор.
  last_name             varchar(150) not null default '',
  first_name            varchar(150) not null default '',
  middle_name           varchar(150) not null default '',

  birth_date            date,
  birth_place           text         not null default '',

  -- Номера хранятся как введены (с пробелами и дефисами): это документ, а не
  -- число. Нормализация под сравнение — забота кода, а не колонки.
  snils                 varchar(20)  not null default '',
  inn                   varchar(20)  not null default '',

  registration_address  text         not null default '',
  actual_address        text         not null default '',

  employer              text         not null default '',
  job_title             text         not null default '',

  phone                 varchar(30)  not null default '',
  email                 varchar(254) not null default '',

  notes                 text         not null default '',

  created_at            timestamptz  not null default now(),
  updated_at            timestamptz  not null default now(),

  constraint person_profile_user_id_key unique (user_id)
);
