-- Веха 2 эпика «Личные данные и Круг Совиных» (заказ владельца 2026-09-03):
-- документ получает ПРОИЗВОЛЬНЫЕ поля и НЕСКОЛЬКО файлов.
--
-- Что было: `documents_document` — плоская строка с девятью фиксированными
-- полями и РОВНО тремя файловыми слотами (front_image / back_image /
-- additional_files, по одному varchar(100) на слот). Второй файл, загруженный
-- в занятый слот, затирал первый. Ни паспорт (много реквизитов, развороты),
-- ни свидетельство (несколько страниц) в эту форму не помещаются.
--
-- Что становится: ядро документа (название, тип, номер, даты, кем выдан)
-- остаётся колонками — это общее у всех документов и по нему идёт поиск;
-- всё остальное человек добавляет сам парами «название поля → значение».
--
-- Старые колонки-слоты НЕ удаляются: `drop column` на живой схеме необратим,
-- а выигрыш — три неиспользуемых varchar. Код с 2026-09-04 их не читает и не
-- пишет; в схеме они помечены рудиментом.

-- Произвольные поля документа: «Серия», «Код подразделения», «Кем выдан»…
-- Значение — text без ограничения формата: это реквизит документа, и его
-- форма записи (пробелы, дефисы, латиница в номере) — часть значения.
create table if not exists document_field (
  id          bigint generated by default as identity primary key,
  document_id bigint       not null references documents_document(id) on delete cascade,
  name        varchar(100) not null,
  value       text         not null default '',
  -- Порядок задаёт человек перетаскиванием строк в форме; в распечатке поля
  -- идут в этом же порядке, поэтому он хранится, а не вычисляется.
  position    integer      not null default 0,
  created_at  timestamptz  not null default now()
);

create index if not exists document_field_document_id_idx on document_field (document_id, position);

-- Файлы документа: многостраничный скан, развороты, выгрузка из госуслуг.
-- Путь относительный, как и раньше (`documents/<userId>/<docId>/<token>.<ext>`),
-- но теперь их много и слот в имени не участвует.
create table if not exists document_file (
  id            bigint       generated by default as identity primary key,
  document_id   bigint       not null references documents_document(id) on delete cascade,
  path          varchar(255) not null,
  -- Имя, под которым файл принесли: «паспорт разворот 2.jpg». Нужно и в
  -- интерфейсе, и в ZIP-выгрузке — там путь на диске человеку не читаем.
  original_name varchar(255) not null default '',
  mime          varchar(100) not null default '',
  size_bytes    integer      not null default 0,
  position      integer      not null default 0,
  created_at    timestamptz  not null default now()
);

create index if not exists document_file_document_id_idx on document_file (document_id, position);
