-- Веха 3 эпика: Круг — общее пространство родни ПО СОГЛАСИЮ.
--
-- Модель выбрана владельцем 2026-09-03 из двух предложенных: «круг с согласием»
-- (владелец приглашает, человек подтверждает участие у себя, участники видят
-- друг друга) вместо попарных разрешений. Причина выбора — объяснимость: в
-- круге один вопрос «ты в кругу?» с одним ответом, а попарная матрица требует
-- от каждого держать в голове, кому он что открыл.
--
-- Ключевое свойство: членство БЕЗ `consented_at` не даёт ничего. Приглашение —
-- это предложение, а не факт. Владелец круга не может втащить в него человека
-- своей волей, и это не формальность: с 2026-09-03 суперпользователь больше не
-- видит чужие данные в обход (`lib/auth/rbac.ts`), поэтому согласие здесь —
-- единственный способ показать свою карточку кому-то ещё.

create table if not exists circle (
  id            bigint       generated by default as identity primary key,
  -- Имя редактируемое, а не зашитое в код: семья называет себя сама, и
  -- правописание фамилии — не то, что стоит фиксировать миграцией.
  name          varchar(100) not null,
  owner_user_id integer      not null references auth_user(id) on delete cascade,
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now()
);

create index if not exists circle_owner_idx on circle (owner_user_id);

create table if not exists circle_member (
  id           bigint      generated by default as identity primary key,
  circle_id    bigint      not null references circle(id) on delete cascade,
  user_id      integer     not null references auth_user(id) on delete cascade,
  invited_at   timestamptz not null default now(),
  -- NULL — приглашён, но ещё не согласился. Видимость даёт ТОЛЬКО непустое
  -- значение: см. комментарий к таблице.
  consented_at timestamptz,
  -- Отказ хранится отдельно от «ещё не ответил»: иначе приглашение, от которого
  -- отказались, выглядит как новое и всплывает у человека снова и снова.
  -- Отказ обратим — человек может согласиться позже.
  declined_at  timestamptz,
  -- Выход из круга. Строка не удаляется, чтобы повторное приглашение не
  -- выглядело первым и чтобы было видно, что человек уже уходил.
  left_at      timestamptz,
  constraint circle_member_unique unique (circle_id, user_id)
);

create index if not exists circle_member_user_idx on circle_member (user_id);
