-- 0018_family_tree — «Древо семьи» в разделе «Документы» (задача владельца 2026-09-21).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Применяется на
-- проде через psql ДО деплоя (migration-guard в deploy-prod.yml блокирует
-- авто-деплой → деплой через workflow_dispatch).
--
-- Две таблицы. `family_person` — человек древа: ФИО, как зовут в семье, рождение и
-- смерть, где жил, род занятий, национальность, значение фамилии. Даты — СТРОКОЙ
-- (`born`, `died`), не date: про прадеда известно «примерно 1900-е», про бабушку —
-- только год, и колонка date заставила бы либо врать точной датой, либо оставлять
-- пусто. `family_relation` — связь двух людей: `parent` (from — родитель, to —
-- ребёнок) или `spouse` (пара, порядок не важен). Всё остальное родство (братья,
-- дяди, прадеды, тесть) ВЫЧИСЛЯЕТСЯ из этих двух видов — хранить «дядя» отдельной
-- строкой значило бы хранить вывод рядом с посылками, и они разошлись бы.
--
-- Люди древа — не аккаунты и не круг: у прадеда аккаунта нет и не будет. Строка
-- принадлежит владельцу (`user_id`), чужое древо никому не видно. `holder` —
-- необязательная привязка к строке «чей документ» из `documents_document.holder`,
-- чтобы с человека в древе можно было перейти к его документам.

BEGIN;

CREATE TABLE IF NOT EXISTS family_person (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
  last_name        varchar(150) NOT NULL DEFAULT '',
  first_name       varchar(150) NOT NULL DEFAULT '',
  middle_name      varchar(150) NOT NULL DEFAULT '',
  maiden_name      varchar(150) NOT NULL DEFAULT '',
  nickname         varchar(150) NOT NULL DEFAULT '',
  sex              varchar(1)   NOT NULL DEFAULT '',
  born             varchar(100) NOT NULL DEFAULT '',
  birth_place      text         NOT NULL DEFAULT '',
  died             varchar(100) NOT NULL DEFAULT '',
  death_place      text         NOT NULL DEFAULT '',
  residence        text         NOT NULL DEFAULT '',
  occupation       text         NOT NULL DEFAULT '',
  nationality      varchar(100) NOT NULL DEFAULT '',
  surname_meaning  text         NOT NULL DEFAULT '',
  notes            text         NOT NULL DEFAULT '',
  holder           varchar(150) NOT NULL DEFAULT '',
  is_self          boolean      NOT NULL DEFAULT false,
  sort_order       integer      NOT NULL DEFAULT 0,
  created_at       timestamptz  NOT NULL DEFAULT now(),
  updated_at       timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS family_person_user_idx ON family_person(user_id);
COMMENT ON COLUMN family_person.sex IS '''m'' / ''f'' / '''' — нужен для слов родства (дядя/тётя).';
COMMENT ON COLUMN family_person.is_self IS 'Точка отсчёта родства («я»); одна на владельца по смыслу, не по ограничению.';

CREATE TABLE IF NOT EXISTS family_relation (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
  kind        varchar(10) NOT NULL,
  from_id     bigint NOT NULL REFERENCES family_person(id) ON DELETE CASCADE,
  to_id       bigint NOT NULL REFERENCES family_person(id) ON DELETE CASCADE,
  note        varchar(200) NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT family_relation_kind_chk CHECK (kind IN ('parent', 'spouse')),
  CONSTRAINT family_relation_not_self_chk CHECK (from_id <> to_id),
  CONSTRAINT family_relation_uniq UNIQUE (kind, from_id, to_id)
);
CREATE INDEX IF NOT EXISTS family_relation_user_idx ON family_relation(user_id);
COMMENT ON COLUMN family_relation.kind IS 'parent: from — родитель, to — ребёнок. spouse: пара, порядок не важен.';

COMMIT;
