-- 0021_hotline_relay — таблицы HTTP-relay Телефона (Ф1, мандат brain 04.10).
--
-- РУКОПИСНАЯ миграция (KARMAN не гоняет drizzle-kit generate). Применяется на
-- проде через psql ДО деплоя (migration-guard в deploy-prod.yml блокирует
-- авто-деплой → деплой через workflow_dispatch).
--
-- Две таблицы. `hotline_message` — сообщения relay: комната, отправитель, вид,
-- текст. `hotline_presence` — присутствие: метка → «жив до». Комнаты в v2-a —
-- ПРОСТРАНСТВА ИМЁН, а не криптографические границы: общий секрет relay один на
-- всех бэкендов-участников (как trust Ф0, где все ленты лежат в одном репо).
-- Персональные токены комнат — v2-b; до него любой держатель секрета технически
-- может читать любую комнату, и это задокументировано, а не пропущено.
--
-- Текст ограничен 2000 символами CHECK'ом на случай обхода валидации приложения:
-- лимит — часть контракта Ф0 (TEXT_LIMIT в hotline.sh), сервер его не расширяет.
-- Секретам в ленте не место дважды: клиентский lint Ф0 + серверный deny-линт
-- (lib/hotline/lint.ts) до записи. Строки НЕ удаляются приложением (история —
-- часть переговоров); ретенция 30 дней — v2-b отдельным заявлением.

BEGIN;

CREATE TABLE IF NOT EXISTS hotline_message (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room             varchar(64)  NOT NULL,
  sender           varchar(64)  NOT NULL,
  kind             varchar(16)  NOT NULL,
  text             varchar(2000) NOT NULL,
  created_at       timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT hotline_message_kind_chk CHECK (kind IN ('question', 'answer', 'done', 'ping', 'wakeup', 'ack')),
  CONSTRAINT hotline_message_text_len_chk CHECK (char_length(text) BETWEEN 1 AND 2000)
);
CREATE INDEX IF NOT EXISTS hotline_message_room_id_idx ON hotline_message (room, id);

CREATE TABLE IF NOT EXISTS hotline_presence (
  label            varchar(64)  NOT NULL PRIMARY KEY,
  alive_until      timestamptz  NOT NULL,
  updated_at       timestamptz  NOT NULL DEFAULT now()
);

COMMIT;
